name: Bug Report
description: Submit a bug
title: "Bug: <Title>"
labels: ["Type: Bug"]
body:
- type: dropdown
  attributes:
    label: What kind of problem is it?
    options: [Bug, Exploit, Other]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear description of what the bug is. Pictures are great!
    placeholder: |
      When I do X then Y happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Map Name
    description: A map that the issue occurs on. 
    placeholder: |
      Please explicitly state what map the issue occurs on.
  validations:
    required: false
- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Open map [...]
      2. Do [...]
      3. Error occurs!
  validations:
    required: true
